config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  resources :pools
  resources :games, only: [:new]
  resources :players do
    resources :entries
  end

  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'
  get 'signup'   => 'players#new'
  get 'new_game'   => 'games#new_game'
  root 'players#show'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :picks
  belongs_to :player
  belongs_to :pool

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :spread
  has_many :picks
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  belongs_to :week

end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :game
  belongs_to :team
  belongs_to :entry

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :entries
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  validates :name, :email, :password, presence: true
  validates :name, :email, uniqueness: true
  validates :email, :format => EMAIL_REGEX

  has_secure_password
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_many :entries
  has_many :players, through: :entries
  has_many :weeks

end

app/models/spread.rb
class Spread < ActiveRecord::Base
  has_one :game
  belongs_to :favorite, class_name: 'Team'

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :games
  has_many :picks

end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :games

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_admin, only: [:new, :new_game]

  def new

  end

  def new_game
    @teams = Team.all
    respond_to do |format|
      if request.xhr?
        format.html { render :new_game, layout: false}
      else
        format.html { render :new_game }
      end
    end
  end

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :get_pool, only: [:show]
  before_action :require_login

  def index

  end

  def show
    respond_to do |format|
      if request.xhr?
        format.html { render :show, layout: false}
      else
        format.html { render :show }
      end
    end
  end

  private

  def get_pool
    @pool = Pool.find_by(id: params[:pool_id])
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then return "alert alert-info"
    when :success then return "alert alert-success"
    when :error then return "alert alert-danger"
    when :alert then return "alert alert-warning"
    end
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spreads_helper.rb
module SpreadsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/games/_form.html.erb
<div class="container">
    <div class='col-sm-2'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker3' tabindex='-1'>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                    <span class="caret"></span>
                </span>
                <input type='text' class="form-control" />
            </div>
        </div>
    </div>
    <select class="selectpicker" title="Away Team">
        <% @teams.each do |team| %>
        <option id='<%=team.abbrev%>-away'><%= "#{team.location} #{team.name}" %></option>
        <% end %>
    </select>
    <select class="selectpicker" title="Home Team">
        <% @teams.each do |team| %>
        <option id='<%=team.abbrev%>-home'><%= "#{team.location} #{team.name}" %></option>
        <% end %>
    </select>
</div>

app/views/games/new.html.erb
<h2>Games</h2>

<div>
  <select class="date-of-week selectpicker" multiple data-selected-text-format="value" title="Choose game days">
    <option class="Tuesday">Tuesday</option>
    <option>Wednesday</option>
    <option>Thursday</option>
    <option>Friday</option>
    <option>Saturday</option>
    <option>Sunday</option>
    <option>Monday</option>
  </select>
</div>

<div id="game-input-container"></div>

app/views/games/new_game.erb
<%= render 'form' %>

app/views/pools/_form.html.erb
<div id="games" class="col-xs-12">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Time</th>
        <th>Away Team</th>
        <th>Home Team</th>
      </tr>
    </thead>
      <tr>
        <td>
          1:00 pm
        </td>
        <td id="away-team-1" class="team-cell">
          <button type="button" class="btn btn-default btn-lg">
          <span class="fa-stack">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i id="away-team-1-chk" class="fa fa-check fa-stack-1x team-select"></i>
          </span>
          NY Giants +4
   </button>
        </td>
        <td id="home-team-1" class="team-cell">
          <button type="button" class="btn btn-default btn-lg">
          <span class="fa-stack">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i id="home-team-1-chk"class="fa fa-check fa-stack-1x team-select"></i>
          </span>
          Miami Dolphins -4
        </button>
        </td>
      </tr>
      <tr>
        <td>
          1:00 pm
        </td>
        <td id="away-team-2" class="team-cell">
          <span class="fa-stack">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i id="away-team-2-chk"class="fa fa-check fa-stack-1x team-select"></i>
          </span>
          NY Giants +4
        </td>
        <td id="home-team-2" class="team-cell">
          <span class="fa-stack">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i id="home-team-1-chk" class="fa fa-check fa-stack-1x team-select"></i>
          </span>
          Miami Dolphins -4
        </td>
      </tr>
    </table>
  </div>

app/views/pools/show.html.erb
<div id="rules-div">
  <button type="button" id="rules-button" class="btn btn-primary btn-md btn-block">Rules</button>
</div>
<p></p>
<div id="rules-text">
  <div class="col-xs-12" id="game"><p>Game: <span class="games-rules"><%= @pool.name %></span></p></div>
  <div class="col-xs-12" id="picks"><p>Number of picks: <span class="games-rules"><%= @pool.number_of_teams %></span></p></div>
  <div class="col-xs-12" id="description"><p>Rules: <span class="games-rules"><%= @pool.description %></span></p></div>
</div>
<div id='pool-submit'>
  <div class='form-group'>
    <div class='col-sm-12 text-center submit-buttons'>
      <%= button_to 'Submit Picks', new_player_path, class:'btn btn-default btn-lg pool-submit-button', method: 'POST' %>
    </div>
  </div>
</div>
<div id="pool-progress-bar">
<!--   <div class="progress">
    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
      <span class="sr-only">60% Complete (warning)</span>
    </div>
  </div> -->
</div>
<%= render 'form' %>