config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  resources :pools
  resources :games, only: [:new]
  resources :players do
    resources :entries
  end

  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'
  get 'signup'   => 'players#new'
  get 'new_game'   => 'games#new_game'
  root 'players#show'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :picks
  belongs_to :player
  belongs_to :pool

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :spread
  has_many :picks
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  belongs_to :week

end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :game
  belongs_to :team
  belongs_to :entry

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :entries
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  validates :name, :email, :password, presence: true
  validates :name, :email, uniqueness: true
  validates :email, :format => EMAIL_REGEX

  has_secure_password
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  has_many :entries
  has_many :players, through: :entries
  has_many :weeks

end

app/models/spread.rb
class Spread < ActiveRecord::Base
  has_one :game
  belongs_to :favorite, class_name: 'Team'

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :games
  has_many :picks

end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :games

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_admin, only: [:new, :new_game]

  def new

  end

  def new_game
    @teams = Team.all
    respond_to do |format|
      if request.xhr?
        format.html { render :new_game, layout: false}
      else
        format.html { render :new_game }
      end
    end
  end

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then return "alert alert-info"
    when :success then return "alert alert-success"
    when :error then return "alert alert-danger"
    when :alert then return "alert alert-warning"
    end
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spreads_helper.rb
module SpreadsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/layouts/_flash.html.erb
<div id="flash_msg_container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="brand-color" class="navbar-brand" href="#">chop<i class="fa fa-bolt"></i>op</a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active" id="profile"><a href="#">Profile <span class="sr-only">(current)</span></a></li>
          <li class="dropdown" id="pools">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pools <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a id="4-for-4" href="?pool_id=1">4 for 4</a></li>
              <li role="separator" class="divider"></li>
              <li><a id="6-for-6" href="?pool_id=2">6 for 6</a></li>
              <li role="separator" class="divider"></li>
              <li><a id="knockout" href="?pool_id=3">Knockout</a></li>
              <li role="separator" class="divider"></li>
              <li><a id="streak" href="?pool_id=4">Streak</a></li>
            </ul>
          </li>
          <li id="results"><a href="#">Results</a></li>
          <li id="messages"><a href="#">Messages</a></li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign Out', signout_path %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>chop/op</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Josefin+Sans|Sanchez|Titillium+Web:900' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if @current_user %>
  <%= render 'layouts/nav' %>
  <%= render 'layouts/flash' %>
<% else %>
  <div id="login-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="active item one"></div>
      <div class="item two"></div>
    </div>
  </div>
  <div class='login-div'><a href=''>chop <i class="fa fa-bolt"></i>op</a></div>
  <%= render 'layouts/flash' %>
<% end %>

<div class="page-content">
  <%= yield %>
</div>

</body>
</html>